// import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Nav from "@/layouts/Nav/Nax";

const monst = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
//
export const metadata = {
  title: "TreeStar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monst.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
