// import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Nav from "@/layouts/Nav/Nav";
import Footer from "@/layouts/Footer/Footer";
import { ThemeProvider } from './../context/ThemeContext';
import Darkmode from '@/components/DarkToggleBtn'

const monst = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "TreeStar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monst.className}>
      <ThemeProvider>
      <Darkmode />
        <Nav />
        {children}
        <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
